#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

START_DATE="${START_DATE:-2025-11-01}"
END_DATE="${END_DATE:-2025-11-30}"
SYMBOL_LIMIT="${SYMBOL_LIMIT:-100}"
THETADATA_MAX_CONCURRENT_CONNECTIONS="${THETADATA_MAX_CONCURRENT_CONNECTIONS:-4}"
DOWNLOAD_WORKERS="${DOWNLOAD_WORKERS:-$THETADATA_MAX_CONCURRENT_CONNECTIONS}"
ENRICH_WORKERS="${ENRICH_WORKERS:-4}"
BACKFILL_FORCE="${BACKFILL_FORCE:-0}"
BACKFILL_RAM_BUDGET_MB="${BACKFILL_RAM_BUDGET_MB:-10240}"
BACKFILL_NODE_MAX_OLD_SPACE_MB="${BACKFILL_NODE_MAX_OLD_SPACE_MB:-1024}"
DOWNLOAD_SUPPLEMENTAL_CONCURRENCY="${DOWNLOAD_SUPPLEMENTAL_CONCURRENCY:-2}"
ENRICH_SUPPLEMENTAL_CONCURRENCY="${ENRICH_SUPPLEMENTAL_CONCURRENCY:-2}"
THETADATA_STREAM_IDLE_TIMEOUT_MS="${THETADATA_STREAM_IDLE_TIMEOUT_MS:-1800000}"
THETADATA_STREAM_HEARTBEAT_EVERY_ROWS="${THETADATA_STREAM_HEARTBEAT_EVERY_ROWS:-250000}"
CLICKHOUSE_ENRICH_STREAM_READ="${CLICKHOUSE_ENRICH_STREAM_READ:-1}"
CLICKHOUSE_ENRICH_STREAM_WRITE="${CLICKHOUSE_ENRICH_STREAM_WRITE:-1}"
CLICKHOUSE_ENRICH_STREAM_CHUNK_SIZE="${CLICKHOUSE_ENRICH_STREAM_CHUNK_SIZE:-8000}"
PIPELINE_STAGE_OVERLAP="${PIPELINE_STAGE_OVERLAP:-1}"

TS="$(date +%Y%m%dT%H%M%S)"
SYMBOL_DAY_LIST_PATH="${BACKFILL_SYMBOL_DAY_LIST_PATH:-$PROJECT_ROOT/artifacts/reports/symbol-days-top${SYMBOL_LIMIT}-${START_DATE//-/}-${END_DATE//-/}-${TS}.tsv}"
OPEN_DAYS_PATH="${OPEN_DAYS_OUTPUT_PATH:-$PROJECT_ROOT/artifacts/reports/open-days-${START_DATE//-/}-${END_DATE//-/}-${TS}.tsv}"

echo "Generating symbol-day list..."
(
  cd "$PROJECT_ROOT"
  START_DATE="$START_DATE" \
  END_DATE="$END_DATE" \
  SYMBOL_LIMIT="$SYMBOL_LIMIT" \
  OUTPUT_PATH="$SYMBOL_DAY_LIST_PATH" \
  OPEN_DAYS_OUTPUT_PATH="$OPEN_DAYS_PATH" \
  THETADATA_BASE_URL="${THETADATA_BASE_URL:-http://127.0.0.1:25503}" \
  node scripts/backfill/generate-symbol-days-topn-range.js
)

echo "Running pipeline backfill..."
(
  cd "$PROJECT_ROOT"
  BACKFILL_MODE="full" \
  BACKFILL_FORCE="$BACKFILL_FORCE" \
  BACKFILL_SYMBOL_DAY_LIST_PATH="$SYMBOL_DAY_LIST_PATH" \
  THETADATA_MAX_CONCURRENT_CONNECTIONS="$THETADATA_MAX_CONCURRENT_CONNECTIONS" \
  DOWNLOAD_WORKERS="$DOWNLOAD_WORKERS" \
  ENRICH_WORKERS="$ENRICH_WORKERS" \
  DOWNLOAD_SUPPLEMENTAL_CONCURRENCY="$DOWNLOAD_SUPPLEMENTAL_CONCURRENCY" \
  ENRICH_SUPPLEMENTAL_CONCURRENCY="$ENRICH_SUPPLEMENTAL_CONCURRENCY" \
  BACKFILL_RAM_BUDGET_MB="$BACKFILL_RAM_BUDGET_MB" \
  BACKFILL_NODE_MAX_OLD_SPACE_MB="$BACKFILL_NODE_MAX_OLD_SPACE_MB" \
  THETADATA_STREAM_IDLE_TIMEOUT_MS="$THETADATA_STREAM_IDLE_TIMEOUT_MS" \
  THETADATA_STREAM_HEARTBEAT_EVERY_ROWS="$THETADATA_STREAM_HEARTBEAT_EVERY_ROWS" \
  CLICKHOUSE_ENRICH_STREAM_READ="$CLICKHOUSE_ENRICH_STREAM_READ" \
  CLICKHOUSE_ENRICH_STREAM_WRITE="$CLICKHOUSE_ENRICH_STREAM_WRITE" \
  CLICKHOUSE_ENRICH_STREAM_CHUNK_SIZE="$CLICKHOUSE_ENRICH_STREAM_CHUNK_SIZE" \
  PIPELINE_STAGE_OVERLAP="$PIPELINE_STAGE_OVERLAP" \
  bash scripts/backfill/backfill-clickhouse-historical-days-pipeline.sh
)

echo "Backfill range complete."
echo "Symbol-day list: $SYMBOL_DAY_LIST_PATH"
echo "Open-days list: $OPEN_DAYS_PATH"
