#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
cd "$ROOT_DIR"

PARQUET_DOWNLOAD_WORKERS="${PARQUET_DOWNLOAD_WORKERS:-8}"
PARQUET_COMPUTE_WORKERS="${PARQUET_COMPUTE_WORKERS:-1}"
PARQUET_THETA_MAX_CONCURRENT_CONNECTIONS="${PARQUET_THETA_MAX_CONCURRENT_CONNECTIONS:-8}"
PARQUET_THETA_ACTIVE_TARGET="${PARQUET_THETA_ACTIVE_TARGET:-8}"
PARQUET_THETA_QUEUED_TARGET="${PARQUET_THETA_QUEUED_TARGET:-16}"
PARQUET_HEAVY_DOWNLOAD_WORKERS="${PARQUET_HEAVY_DOWNLOAD_WORKERS:-2}"
PARQUET_HEAVY_DOWNLOAD_SYMBOLS="${PARQUET_HEAVY_DOWNLOAD_SYMBOLS:-SPX,SPXW,SPY,QQQ,VIX,VIXW,RUT,RUTW,XSP}"
PARQUET_PUBLISH_ON_SUCCESS="${PARQUET_PUBLISH_ON_SUCCESS:-0}"

run_month() {
  local run_id="$1"
  local start_date="$2"
  local end_date="$3"

  echo
  echo "=== Trade backfill month: $run_id ($start_date -> $end_date) ==="

  START_DATE="$start_date" \
  END_DATE="$end_date" \
  PARQUET_RUN_ID="$run_id" \
  PARQUET_DOWNLOAD_WORKERS="$PARQUET_DOWNLOAD_WORKERS" \
  PARQUET_COMPUTE_WORKERS="$PARQUET_COMPUTE_WORKERS" \
  PARQUET_THETA_MAX_CONCURRENT_CONNECTIONS="$PARQUET_THETA_MAX_CONCURRENT_CONNECTIONS" \
  PARQUET_THETA_ACTIVE_TARGET="$PARQUET_THETA_ACTIVE_TARGET" \
  PARQUET_THETA_QUEUED_TARGET="$PARQUET_THETA_QUEUED_TARGET" \
  PARQUET_HEAVY_DOWNLOAD_WORKERS="$PARQUET_HEAVY_DOWNLOAD_WORKERS" \
  PARQUET_HEAVY_DOWNLOAD_SYMBOLS="$PARQUET_HEAVY_DOWNLOAD_SYMBOLS" \
  PARQUET_PUBLISH_ON_SUCCESS="$PARQUET_PUBLISH_ON_SUCCESS" \
  bash "$ROOT_DIR/apps/flow-api/scripts/parquet/run-jan2025-week-benchmark.sh"
}

run_month "parquet-jan2025-full-20260325T121240Z" "2025-01-02" "2025-01-31"
run_month "parquet-feb2025-20260324T061500Z" "2025-02-03" "2025-02-28"
run_month "parquet-theta-march-full-split8-live-20260326T223019Z" "2025-03-03" "2025-03-31"
